#!/bin/bash
# Cleanup script: 15 worktrees confirmed superseded by already-merged PRs on origin/main.
# Generated by Claude during worktree deep audit, 2026-09-30. Run from repo root.
# Rewritten for bash 3.2 (macOS default) compatibility - no associative arrays.
set -e
cd /Users/nikhilsoman/dev/synlynk

ENTRIES="
job-ee42c9eb /Users/nikhilsoman/dev/synlynk/worktrees/job-ee42c9eb
job-16d2932b /Users/nikhilsoman/dev/synlynk/worktrees/job-16d2932b
job-1ac39856 /Users/nikhilsoman/dev/synlynk/worktrees/job-1ac39856
job-468b44c3 /Users/nikhilsoman/dev/synlynk/worktrees/job-468b44c3
job-4d18c521 /Users/nikhilsoman/dev/synlynk/worktrees/job-4d18c521
job-97154a4d /Users/nikhilsoman/dev/synlynk/worktrees/job-97154a4d
job-55e911c7 /Users/nikhilsoman/dev/synlynk/worktrees/job-55e911c7
job-74cd93fa /Users/nikhilsoman/dev/synlynk/worktrees/job-74cd93fa
job-cfbd0a98 /Users/nikhilsoman/dev/synlynk/worktrees/job-cfbd0a98
job-1c752df4 /Users/nikhilsoman/dev/synlynk/.claude/worktrees/chore.discord-herdr-bridge-spec/worktrees/job-1c752df4
job-dcdddcfc /Users/nikhilsoman/dev/synlynk/.claude/worktrees/chore.discord-herdr-bridge-spec/worktrees/job-dcdddcfc
job-56b6f055 /Users/nikhilsoman/dev/synlynk/.claude/worktrees/chore.discord-herdr-bridge-spec/worktrees/job-56b6f055
job-c33611da /Users/nikhilsoman/dev/synlynk/.claude/worktrees/chore.discord-herdr-bridge-spec/worktrees/job-c33611da
job-2caf4ba1 /Users/nikhilsoman/dev/synlynk/worktrees/job-2caf4ba1
job-f778c80c /Users/nikhilsoman/dev/synlynk/worktrees/job-f778c80c
"

echo "$ENTRIES" | while read -r jid path; do
  [ -z "$jid" ] && continue
  if [ ! -d "$path" ]; then
    echo "SKIP $jid - path not found (already removed?)"
    continue
  fi
  branch=$(git -C "$path" branch --show-current 2>/dev/null)
  dirty=$(git -C "$path" status --short 2>/dev/null | wc -l | tr -d ' ')
  if [ "$dirty" != "0" ]; then
    echo "SKIP $jid ($branch) - dirty ($dirty files), needs review"
    continue
  fi
  git worktree remove "$path" --force 2>&1 | sed "s/^/[$jid] /"
  git branch -D "$branch" 2>&1 | sed "s/^/[$jid] /"
  if git ls-remote --heads origin "$branch" 2>/dev/null | grep -q .; then
    git push origin --delete "$branch" 2>&1 | sed "s/^/[$jid] remote-/"
  fi
done
echo "=== done ==="
git worktree list
